# short names
[[rename_node]]
match = "(解锁|)(\\|)(x.*)(\\|V2ray)"
replace = "$[$3]"

[[rename_node]]
match = "(..|...)(\\d\\d\\d\\d|\\d\\d\\d)(\\|)(Azure|HKT|CN2GIA)"
replace = "$1$4$2"

[[rename_node]]
match = "^CordCloud - "
replace = ""

[[rename_node]]
match = "(标准)|(标准线路)|(线路)|(中转)|(直连)|(80端口)|(V\\d-)|(IEPL专线 )|(IPV6)|(\\(海外\\|新疆专用\\))|(\\(\u6d77\u5916\\|\u65b0\u7586\u4e13\u7528\\))"
replace = ""

[[rename_node]]
match = "(.*)( )(.*\\d)( \\| )(.*)"
replace = "$1$3$5"

[[rename_node]]
match = "(流媒体)|(-M)|(原生IP)|(解锁)"
replace = "[M]"

[[rename_node]]
match = "(.*)(\\d.*\\d)(静态解锁|动态解锁|原生解锁|解锁|动态原生|静态原生|原生)"
replace = "$1$2[M]"

[[rename_node]]
match = "(.*)(\\d.*\\d)(\\|[\\w].*\\d)"
replace = "$1$2"

[[rename_node]]
match = "(.*)(NO)(.?\\d*\\d)$"
replace = "$1 $3"

[[rename_node]]
match = "((CN\\d•)|^)(⓪|❶|❷|❸|❻)(TJ\\.|gR\\.|V2\\.|H2\\.|SS\\.)"
replace = ""

[[rename_node]]
match = "^(.*)(HK(?!B|G|T))([\u4e00-\u9fa5].*)"
replace = "香港 $3"

[[rename_node]]
match = "^(HK)(\\d.*)"
replace = "香港 $2"

[[rename_node]]
match = "^(HKBN)(.*)"
replace = "香港HKBN $2"

[[rename_node]]
match = "^(HKG)(.*)"
replace = "香港HKG $2"

[[rename_node]]
match = "^(HKT)(.*)"
replace = "香港HKT $2"

[[rename_node]]
match = "^(HGC)(.*)"
replace = "香港HGC $2"

[[rename_node]]
match = "^(WTT)(.*)"
replace = "香港WTT $2"

[[rename_node]]
match = "^(US)(.*)"
replace = "美国 $2"

[[rename_node]]
match = "^(JP)(.*)"
replace = "日本 $2"

[[rename_node]]
match = "^(TW)(.*)"
replace = "台湾 $2"

[[rename_node]]
match = "^(SG)(.*)"
replace = "新加坡 $2"

[[rename_node]]
match = "^(RU)(.*)"
replace = "俄罗斯 $2"

[[rename_node]]
match = "^(TR)(.*)"
replace = "土耳其 $2"

[[rename_node]]
match = "^(UK)(.*)"
replace = "英国 $2"

[[rename_node]]
match = "^(KR)(.*)"
replace = "韩国 $2"

[[rename_node]]
match = "^(FR)(.*)"
replace = "法国 $2"

[[rename_node]]
match = "^(CA)(.*)"
replace = "加拿大 $2"

[[rename_node]]
match = "^(CN)(.*)"
replace = "中国 $2"

[[rename_node]]
match = "^(RO)(.*)"
replace = "罗马尼亚 $2"

[[rename_node]]
match = "^(BR)(.*)"
replace = "巴西 $2"

[[rename_node]]
match = "商宽"
replace = ""

[[rename_node]]
match = "移动"
replace = "CM"

[[rename_node]]
match = "电信"
replace = "CT"

[[rename_node]]
match = "联通"
replace = "CU"

[[rename_node]]
match = "深港专线"
replace = "深港"

[[rename_node]]
match = "(转)"
replace = "▷"

[[rename_node]]
match = "\\d组"
replace = ""

[[rename_node]]
match = "(--)"
replace = ""

[[rename_node]]
match = "(◆)"
replace = ""

[[rename_node]]
match = "((\\|NF)|(\\|NF\\*)|(\\|BBC)|(\\|abema)|(\\|动画疯)|(\\|Netflix)|(\\|動畫瘋)|(\\|Hulu)|(\\|\\[注册Netflix\\])|(\\|HBO)|(\\|TVB)|(\\|D\\+)|(\\|Yp)|(\\|Y2B P)|(\\|AI)|(解锁流媒体)|(原生IP))"
replace = "[M]"

[[rename_node]]
match = "\\[M\\].*\\[M\\]"
replace = "[M]"

[[rename_node]]
match = "\\[CM\\]|\\[CU\\]|\\[BT\\/PT专用\\]|\\[荐\\]|\\[Beta\\]|\\[移动\\]|\\[联通\\]|\\[综合\\]|\\[备用\\]|\\[阿里云\\]|\\[测试\\]|\\[v6\\]|高速|100m限速|CDN加速|Game|PPCW|Sakura"
replace = ""

# [[rename_node]]
# match = "(?!<=[\\]|\\)])$"
# replace = "[x1]"

[[rename_node]]
match = "(x|X)(\\d*.?\\d*\\d)"
replace = "[x$2]"

[[rename_node]]
match = "(.*)(\\[)(倍率:)(.*\\d)(\\])"
replace = "$1[x$4]"

[[rename_node]]
match = "(\\[x.*\\d\\])(.*)"
replace = "$2$1"

[[rename_node]]
match = "(.*)( )(.*\\d)(倍率)"
replace = "$1[x$3]"

[[rename_node]]
match = "(.*)(\\|)(x.*\\d)(倍率)"
replace = "$1[$3]"

[[rename_node]]
match = "(.*)( )(x.*\\d)"
replace = "$1[$3]"

[[rename_node]]
match = "\\[\\]"
replace = ""

[[rename_node]]
match = "\\(?((x|X)?(\\d+)(\\.?\\d+)?)((\\s?倍率?)|(x|X))\\)?"
replace = "[x$1]"
